### ISSUE TITLE
[BUG] A critical typo in the code

### ISSUE THREAD

**Issue by FoliageOwO** [GooGuJiang/gugu-ss#1]
# Describe the bug

In the main program code file `main.c`, there is a **typo** in the name of the function `instertSort`.

On searching for the word `instert` on the ***Cambridge Dictionary***, I found that the word does not exist in the world, as the image shows below:

![image](https://github.com/user-attachments/assets/8b23b889-8f54-4a6e-9f2f-b110f1bb8a20)

After investigating the word and the code from this repository and understanding the progress and its function in the function with the name `instertSort`, I did uckily find that a word in the ***Cambridge Dictionary*** with a similar spell does means the same thing done in the code:

![image](https://github.com/user-attachments/assets/7f231ed6-1f25-42e5-9bf0-e291007ce0ca)

IMHO, I think the word `instert` may be misspelled, as the reasonings I mentioned above.

# Steps to reproduce

1. Open the same repository on the **Github** following this link: (GooGuJiang/gugu-ss)[https://github.com/GooGuJiang/gugu-ss].
2. Follow the file path: `(the main branch root directory)/哇，是排序算法/main.c`.
3. Open the file, and check out the function name as follows:

https://github.com/GooGuJiang/gugu-ss/blob/1a58b12a295c4c2fa17b5a35ce8252e9bf89d2a9/%E5%93%87%EF%BC%8C%E6%98%AF%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95/main.c#L11

# Expected behavior

The function name should be correct, so as the function can tell others the proper behavior of the function I just mentioned.

EDIT: After researching, the function name **SHOULD BE** **`insertSort`**, instead of `instertSort`.

# Environment

1. Windows Version: Windows 11 23H2 (OS Build 22631.3737) (winver)
2. Microsoft Edge Version: 130.0.2849.46 (Official build) (64-bit) (may not be the latest)

# Logs

*Not provided*

**Comment by GooGuJiang** [comment]
fixed
